name: trigger-docs-build
run-name: Trigger Docs Build

on:
  push:
    branches:
      - main

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    env:
      VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST "$VERCEL_DEPLOY_HOOK_URL"
